"""
Station-to-Region assignments for stations with simple filenames.
Maps station names to Ocean/Region categories.
"""

# Define valid ocean/region combinations
VALID_REGIONS = {
	('Atlantic', 'Other Atlantic'),
	('Atlantic', 'Eastern Atlantic'),
	('Atlantic', 'Florida'),
	('Atlantic', 'Gulf of Mexico'),
	('Atlantic', 'Caribbean'),
	('Atlantic', 'Brazil'),
	('Pacific', 'Eastern Pacific'),
	('Pacific', 'Polynesia'),
	('Pacific', 'US Pacific Remote Islands'),
	('Pacific', 'Micronesia'),
	('Pacific', 'Melanesia'),
	('Pacific', 'East Asia'),
	('Pacific', 'Southeast Asia'),
	('Pacific', 'Coral Triangle'),
	('Pacific', 'Great Barrier Reef'),
	('Pacific', 'Australia'),
	('Indian', 'Middle East'),
	('Indian', 'South Asia'),
	('Indian', 'Western Indian Ocean'),
}

# Station assignments: map (ocean, region) tuples to lists of station names
STATION_ASSIGNMENTS = {
	('Atlantic', 'Other Atlantic'): sorted(['Bermuda', 'Central Bahamas', 'Northern Bahamas', 'Turks and Caicos']),
	('Atlantic', 'Eastern Atlantic'): sorted(['Cape Verde Islands', 'Sao Tome and Principe']),
	('Atlantic', 'Florida'): sorted(['Florida Keys', 'Southeast Florida']),
	('Atlantic', 'Gulf of Mexico'): sorted(['Flower Garden Banks, Texas', 'Veracruz, Mexico', 'Yucatan Peninsula']),
	('Atlantic', 'Caribbean'): sorted(
		[
			'Northwestern Cuba',
			'Northeastern Cuba',
			'Southwestern Cuba',
			'Southeastern Cuba',
			'Cayman Islands',
			'Jamaica',
			'Northern Hispaniola',
			'Southern Hispaniola',
			'Puerto Rico',
			'Virgin Islands',
			'Leeward Caribbean Islands',
			'Windward Caribbean Islands',
			'Trinidad and Tobago',
			'Nearshore Venezuela',
			'Offshore Venezuela',
			'Aruba, Curacao, and Bonaire',
			'La Guajira, Colombia',
			'Colombia Atlantic',
			'Panama Atlantic East',
			'Panama Atlantic West',
			'Costa Rica Atlantic',
			'Nicaragua',
			'Honduras',
			'Belize',
			'Quintana Roo, Mexico',
		]
	),
	('Atlantic', 'Brazil'): sorted(
		[
			'Fernando de Noronha, Brazil',
			'Maracajau, Brazil',
			'Costa dos Corais, Brazil',
			'Todos os Santos, Brazil',
			'Abrolhos Reefs, Brazil',
			'Trinadade and Martim Vaz, Brazil',
			'Buzios, Brazil',
		]
	),
	('Pacific', 'Eastern Pacific'): sorted(
		[
			'El Salvador',
			'Clipperton Island, France',
			'Costa Rica Pacific',
			'Panama Pacific East',
			'Panama Pacific West',
			'Isla del Coco, Costa Rica',
			'Galapagos, Ecuador',
		]
	),
	('Pacific', 'Polynesia'): sorted(
		[
			'Northwestern Hawaiian Islands',
			'Main Hawaiian Islands',
			'Northern Line Islands',
			'Southern Line Islands',
			'Tuvalu',
			'Northern Cook Islands',
			'Samoas',
			'Wallis and Futuna',
			'Northern Tonga',
			'Southern Tonga',
			'Southern Cook Islands',
			'Marquesas Islands',
			'Tuamotu Archipelago',
			'Society Archipelago',
			'Austral Islands',
			'Pitcairn Islands',
			'Easter Island, Chile',
		]
	),
	('Pacific', 'US Pacific Remote Islands'): sorted(['Wake Atoll', 'Johnston Atoll', 'Howland and Baker']),
	('Pacific', 'Micronesia'): sorted(
		[
			'Northern Mariana Islands',
			'Guam',
			'Western FSM',
			'Palau',
			'Eastern FSM',
			'Marshall Islands',
			'Gilbert Islands, Kiribati',
			'Nauru',
			'Phoenix Islands, Kiribati',
		]
	),
	('Pacific', 'Melanesia'): sorted(
		[
			'West Papua',
			'Papua New Guinea',
			'Solomon Islands',
			'Fiji',
			'Vanuatu',
			'Eastern New Caledonia',
			'Western New Caledonia',
			'Chesterfield Islands',
		]
	),
	('Pacific', 'East Asia'): sorted(
		[
			'Northern Ryukyu Islands, Japan',
			'Southern Ryukyu Islands, Japan',
			'Northern Taiwan',
			'Southern Taiwan',
			'Dongsha, Taiwan',
			'Hong Kong, China',
			'Hainan Island, China',
			'Paracel Islands, China',
			'Northern Vietnam',
			'Southern Vietnam',
		]
	),
	('Pacific', 'Southeast Asia'): sorted(
		[
			'Ogasawara Islands',
			'Northern Myanmar',
			'Andaman, India',
			'Southern Myanmar',
			'Great Nicobar, India',
			'Southwestern Thailand',
			'Malacca Strait, Malaysia',
			'Eastern Gulf of Thailand',
			'Western Gulf of Thailand',
			'Spratly Islands',
			'Brunei Darussalam',
			'Northern Borneo, Malaysia',
			'Terengganu, Malaysia',
			'Riau Islands',
			'Johor and Pahang, Malaysia',
			'Singapore Strait',
			'West Kalimantan',
			'Bangka-Belitung Islands',
			'Northwestern Sumatra',
			'Southwestern Sumatra',
			'Lampung and Banten',
			'Northern Java',
			'Southern Java',
		]
	),
	('Pacific', 'Coral Triangle'): sorted(
		[
			'Northern Philippines',
			'Central Philippines',
			'Western Philippines',
			'Eastern Philippines',
			'Southern Philippines',
			'Sabah, Malaysia',
			'North Sulawesi',
			'Central Sulawesi and Gorontalo',
			'East Kalimantan',
			'Southern Borneo',
			'North Maluku, Indonesia',
			'Maluku, Indonesia',
			'West Sulawesi',
			'South Sulawesi',
			'South East Sulawesi',
			'East Java and Bali',
			'West Nusa Tenggara',
			'East Nusa Tenggara',
			'West Timor',
			'Timor-Leste',
		]
	),
	('Pacific', 'Great Barrier Reef'): sorted(
		[
			'Torres Strait',
			'Far Northern GBR',
			'Northern GBR',
			'Central GBR',
			'Southern GBR',
			'Northern Coral Sea Islands',
			'Southern Coral Sea Islands',
		]
	),
	('Pacific', 'Australia'): sorted(
		[
			'Christmas Island, Australia',
			'Pulu Keeling, Australia',
			'Gulf of Carpentaria',
			'Northern Territory',
			'Beagle Gulf',
			'Scott to Ashmore Reefs',
			'North Western Australia',
			'Rowley Shoals',
			'Central Western Australia',
			'Ningaloo',
			'Shark Bay',
			'Hamelin Pool',
			'Houtman Abrolhos',
			'Marmion and Rottnest Island',
			'Moreton Bay, Australia',
			'Lord Howe Island, Australia',
			'Norfolk Island, Australia',
		]
	),
	('Indian', 'Middle East'): sorted(
		[
			'Western Persian Gulf',
			'Bahrain',
			'Eastern Persian Gulf',
			'Gulf of Oman',
			'Al Wusta, Oman',
			'Dhofar, Oman',
			'Socotra, Yemen',
			'Eastern Yemen',
			'Aden, Yemen',
			'Gulf of Tadjoura, Djubouti',
			'Western Yemen',
			'Eritrea',
			'Jazan, Saudi Arabia',
			'Sudan',
			'Tabuk, Saudi Arabia',
			'Al Madinah and Makkah',
			'Gulf of Aqaba',
			'Egypt',
			'Gulf of Suez',
		]
	),
	('Indian', 'South Asia'): sorted(
		[
			'Gulf of Kutch, India',
			'Western India',
			'Kerala, India',
			'Lakshadweep, India',
			'Gulf of Mannar',
			'Southern Sri Lanka',
			'Eastern Sri Lanka',
			'Southeastern India',
			'Maldives',
			'Chagos Archipelago, UK',
		]
	),
	('Indian', 'Western Indian Ocean'): sorted(
		[
			'Somalia',
			'Kenya',
			'Tanzania',
			'Seychelles',
			'Glorioso Islands',
			'Comoros',
			'Mayotte, France',
			'Northern Mozambique',
			'Central Mozambique',
			'Northwestern Madagascar',
			'Western Madagascar',
			'Bassas da India, France',
			'Southwestern Madagascar',
			'Inhambane, Mozambique',
			'Maputo, Mozambique',
			'South Africa',
			'Northern Mauritius',
			'Southern Mauritius',
			'Northeastern Madagascar',
			'Tromelin and Reunion, France',
			'Southeastern Madagascar',
		]
	),
}
